---
apiVersion: v1
kind: Service
metadata:
  name: flaskclusterapp
  labels:
    app: flaskclusterapp
spec:
  type: LoadBalancer
  selector:
    app: flaskclusterapp
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP