apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskclusterapp
  labels:
    app: flaskclusterapp
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskclusterapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flaskclusterapp
    spec:
      containers:
        - image: dapetoo/flaskappeks:latest
          imagePullPolicy: Always
          name: flaskclusterapp
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"